# -*- coding: utf-8 -*-
"""jm_atividade_pratica_aula5_visualizacao_matplotlib_seaborn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PGfFfn8xniLR3hktZod5EM9xO29RGmGi

# Atividade Prática — Aula 5: Visualização de Dados para Decisões com Matplotlib e Seaborn

Esta atividade foi construída com base nos slides da Aula 5, cujo foco é transformar dados limpos em **gráficos que apoiem decisões**, e não em imagens decorativas. A aula reforça que o bom gráfico reduz esforço cognitivo, responde uma pergunta de negócio e precisa ser claro, comparável, simples e honesto. fileciteturn6file0

## Regras desta atividade
- Você deve **construir os códigos**.
- O notebook orienta os passos, mas não entrega a solução pronta.
- Após cada gráfico principal, escreva uma **interpretação curta** em markdown.
- O gráfico deve ser tratado como parte do seu portfólio: título, unidade, ordenação e mensagem importam. fileciteturn6file0

## Dataset da atividade
Arquivo: `vendas_brasil_clean_aula5.csv`

## 1. Preparação do ambiente

Importe as bibliotecas necessárias para trabalhar com:
- manipulação de dados
- gráficos com Matplotlib
- gráficos com Seaborn

**Sugestão:**
- `pandas`
- `matplotlib.pyplot`
- `seaborn`
"""



# Escreva aqui suas importações
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns



"""## 2. Leitura da base

Leia o arquivo `vendas_brasil_clean_aula5.csv` em um DataFrame chamado `df`.

Depois:
1. exiba as primeiras linhas
2. verifique o tamanho da base
3. confira os tipos das colunas
4. observe quais variáveis podem ser usadas para:
   - comparação
   - tendência
   - distribuição
   - relação entre métricas

"""

# Leia o CSV e faça uma inspeção inicial
df = pd.read_csv('vendas_brasil_clean_aula5.csv')

df.head()
df.shape
df.dtypes

"""## 3. Traduzindo a pergunta em gráfico

A aula destaca que a escolha do gráfico nunca é aleatória: a pergunta define a visualização. fileciteturn6file0

### Tarefa
Preencha em markdown pelo menos 4 exemplos no formato:

- **Pergunta do gestor:** ...
- **Variáveis (Pandas):** ...
- **Tipo de gráfico:** ...
- **Biblioteca sugerida:** ...

Use como referência a matriz mostrada nos slides:
- evolução no tempo → linha
- ranking/comparação entre grupos → barras
- variabilidade e outliers → boxplot
- correlação entre duas métricas → scatter

Pergunta: Qual canal gera mais receita?

Variáveis: canal_venda, receita
Gráfico: barras
Biblioteca: matplotlib

Pergunta: Como a receita varia ao longo do tempo?

Variáveis: mes, receita
Gráfico: linha
Biblioteca: matplotlib

Pergunta: A margem varia por segmento?

Variáveis: segmento, margem_lucro
Gráfico: boxplot
Biblioteca: seaborn

Pergunta: Receita alta significa lucro alto?

Variáveis: receita, lucro
Gráfico: scatter
Biblioteca: matplotlib

## 4. Gráfico de barras horizontais — Qual canal gera mais caixa?

A missão prática do slide pede responder: **qual canal gera mais caixa?** fileciteturn6file0

### Tarefa
1. Agrupe a receita por `canal_venda`
2. Ordene os valores
3. Gere um gráfico de **barras horizontais**
4. Use rótulos e título claros
5. Certifique-se de que a visualização esteja limpa e fácil de ler

### Lembretes da aula
- barras são o padrão-ouro para rankings e comparações
- ordenação é obrigatória para facilitar a leitura
- se os rótulos forem longos, barras horizontais ajudam
"""

# Construa aqui o gráfico de barras horizontais por canal_venda
receita_canal = df.groupby('canal_venda')['receita'].sum().sort_values()

receita_canal.plot(kind='barh')
plt.title('Marketplace lidera a geração de receita')
plt.xlabel('Receita')
plt.ylabel('Canal de Venda')
plt.show()

"""### Insight obrigatório
Escreva 2 ou 3 linhas explicando:
- qual canal lidera
- qual canal fica atrás
- que ação tática um gestor poderia considerar a partir disso


O canal Marketplace lidera a receita, enquanto canais como televendas ficam atrás.
Um gestor poderia investir mais no canal líder ou melhorar os canais com baixo desempenho.

## 5. Gráfico de linha — Como é a sazonalidade ao longo dos meses?

Os slides destacam que linhas servem para tendência e sazonalidade, desde que o eixo X seja uma série temporal contínua e formatada. fileciteturn6file0

### Tarefa
1. Agrupe a `receita` por `mes`
2. Gere um gráfico de linha temporal
3. Remova ruídos visuais desnecessários
4. Use um título que diga **o que aconteceu**, não apenas o nome das colunas

### Dica
Pense na diferença entre:
- “Receita por mês”
- “Receita acelera no fim do ano”
"""

# Construa aqui o gráfico de linha temporal da receita por mês
receita_mes = df.groupby('mes')['receita'].sum()

receita_mes.plot(kind='line', marker='o')
plt.title('Receita cresce no final do ano')
plt.xlabel('Mês')
plt.ylabel('Receita')
plt.xticks(rotation=45)
plt.show()

"""### Insight obrigatório
Responda:
- existe sazonalidade?
- há meses de pico?
- o título do seu gráfico ajuda o gestor a entender rapidamente a mensagem?

Existe sazonalidade, com picos nos últimos meses do ano.
Isso indica que campanhas e estoque devem ser reforçados nesse período.

## 6. Boxplot — A margem oscila por segmento?

Os slides mostram que boxplot é adequado quando a pergunta envolve **variabilidade, consistência e outliers**. fileciteturn6file0

### Tarefa
1. Use `segmento` no eixo categórico
2. Use `margem_lucro` como variável numérica
3. Gere um **boxplot** com Seaborn
4. Observe dispersão, mediana e possíveis outliers

### Perguntas
- Qual segmento parece mais estável?
- Existe maior risco ou variabilidade em algum deles?
- Há outliers relevantes?
"""

# Construa aqui o boxplot de margem_lucro por segmento
sns.boxplot(x='segmento', y='margem_lucro', data=df)
plt.title('Margem varia bastante entre segmentos')
plt.show()

"""### Insight obrigatório
Explique, em linguagem de negócio:
- onde parece haver mais consistência
- onde parece haver mais risco
- como isso pode influenciar uma decisão comercial

Alguns segmentos apresentam maior consistência (menos variação), enquanto outros têm mais risco.
Segmentos mais estáveis são melhores para previsibilidade financeira.

## 7. Scatter plot — Produto que fatura muito, dá lucro?

A aula propõe usar scatter quando queremos investigar **relação entre duas métricas** e enxergar densidade com transparência (`alpha`). fileciteturn6file0

### Tarefa
1. Gere um scatter com:
   - eixo X: `receita`
   - eixo Y: `lucro`
2. Use transparência para melhorar a leitura
3. Observe se existe correlação
4. Procure anomalias: pontos com alta receita e lucro ruim, por exemplo

### Perguntas
- A relação entre receita e lucro parece positiva?
Existe uma relação positiva entre receita e lucro.
- Existem exceções preocupantes?
há pontos fora da curva com alta receita e com baixo lucro, que precisam ser investigados.
"""

# Construa aqui o scatter plot entre receita e lucro
plt.scatter(df['receita'], df['lucro'], alpha=0.5)
plt.title('Receita alta geralmente gera mais lucro')
plt.xlabel('Receita')
plt.ylabel('Lucro')
plt.show()

"""## 8. Comunicação vs. decoração

A aula mostra que visualização não é estética pela estética. O gráfico deve reduzir esforço cognitivo e responder uma pergunta de negócio. fileciteturn6file0

### Tarefa
Escolha um dos gráficos que você produziu e revise:
- título
- nome dos eixos
- unidade numérica
- ordenação
- excesso de linhas, bordas ou legendas

Depois escreva:
1. O que você removeu?
excesso de linhas e elementos visuais
2. O gráfico ficou mais fácil de interpretar?
O gráfico ficou  mais limpo e fácil de entender
"""

# Refaça aqui um dos gráficos com foco em simplicidade e clareza
receita_canal = df.groupby('canal_venda')['receita'].sum().sort_values()

plt.figure()
receita_canal.plot(kind='barh')

plt.title('Canal com maior geração de receita')
plt.xlabel('Receita total')
plt.ylabel('Canal de venda')

plt.grid(axis='x')
plt.tight_layout()

plt.show()

"""## 9. Comparabilidade e honestidade

Os slides alertam para dois pontos críticos:
- ordenar rankings melhora comparabilidade
- truncar eixos distorce a percepção e quebra a confiança do usuário fileciteturn6file0

### Tarefa
Responda em markdown:

1. Por que ordenar barras é importante?

Ordenar barras facilita comparar rapidamente

2. Por que truncar o eixo Y pode ser antiético ou enganoso?

Truncar eixo distorce a percepção e engana

3. Em que tipo de gráfico a base zero é especialmente importante?

ase zero é essencial em gráfico de barras

## 10. Galeria dos vilões

A aula apresenta três “vilões” que devem ser evitados:
- pizza caótica
- distorção 3D
- arco-íris sem propósito fileciteturn6file0

### Tarefa
Explique, em markdown:
1. Por que gráfico de pizza com muitas categorias costuma falhar?

Pizza com muitas categorias confunde

2. Por que o 3D atrapalha comparações?

3D dificulta comparação

3. Por que usar muitas cores sem intenção gera confusão cognitiva?

Muitas cores geram poluição visual

## 11. Storytelling — O gráfico não fala sozinho

Um dos pontos mais fortes da aula é que **o título ideal é a conclusão da análise**, e não só a descrição dos eixos. fileciteturn6file0

### Tarefa
Escolha **dois gráficos** que você criou e escreva:
- um título meramente descritivo
- um título analítico, orientado ao insight

Exemplo de lógica:
- Descritivo: “Receita e lucro por canal”
- Analítico: “Online lidera receita, mas Loja Física retém maior margem”

Descritivo: Receita por canal
Analítico: Marketplace domina a geração de receita

Descritivo: Receita por mês
Analítico: Receita dispara no fim do ano

## 12. Missão prática — Case Varejo Brasil

O slide da missão prática propõe três perguntas centrais: fileciteturn6file0

1. Qual canal gera mais caixa?
2. Como é nossa sazonalidade ao longo dos meses?
3. Nosso mix corporativo é mais estável que o varejo?

### Sua tarefa final
Organize o notebook para entregar, no mínimo:
- 1 gráfico de barras horizontais
- 1 gráfico de linha
- 1 boxplot
- 1 scatter plot
- 1 parágrafo curto abaixo de cada gráfico explicando o insight
"""

receita_canal = df.groupby('canal_venda')['receita'].sum().sort_values()

plt.figure()
receita_canal.plot(kind='barh')

plt.title('Canal com maior geração de receita')
plt.xlabel('Receita total')
plt.ylabel('Canal de venda')

plt.grid(axis='x')
plt.tight_layout()
plt.show()

sns.boxplot(x='segmento', y='margem_lucro', data=df)

plt.title('Comparação de margem entre segmentos')
plt.tight_layout()
plt.show()

plt.figure()
plt.scatter(df['receita'], df['lucro'], alpha=0.5)

plt.title('Relação entre receita e lucro')
plt.xlabel('Receita')
plt.ylabel('Lucro')

plt.grid()
plt.tight_layout()
plt.show()

"""## 13. Checklist do analista profissional

Antes de terminar, revise seu trabalho com base no checklist da aula: fileciteturn6file0

- O gráfico responde claramente à pergunta original?
 Sim

- Você removeu linhas, bordas e legendas que não agregam?

Grafico ficou limpo

- Os eixos estão honestos e não distorcem a realidade?

Eixos corretos

- As cores foram usadas com intenção?

Sim

- Há um pequeno texto explicando o insight?

Tem insights

### Tarefa
Responda esse checklist em markdown, item por item.

## 14. Desafio extra (opcional)

Crie um gráfico adicional, escolhendo uma destas possibilidades:
- receita por UF (barras ordenadas)
- lucro por categoria (barras horizontais)
- distribuição de receita por segmento (boxplot)
- relação entre quantidade e lucro (scatter)

Mas atenção:
- o gráfico precisa responder uma pergunta real
- o título precisa ser analítico
- o texto interpretativo é obrigatório
"""

# Desafio extra opcional
receita_uf = df.groupby('uf')['receita'].sum().sort_values()

plt.figure()
receita_uf.plot(kind='barh')

plt.title('Estados do Sudeste lideram a geração de receita')
plt.xlabel('Receita total')
plt.ylabel('UF')

plt.grid(axis='x')
plt.tight_layout()
plt.show()

"""Os estados com maior receita se concentram principalmente em regiões mais desenvolvidas economicamente, indicando que fatores como população, renda e infraestrutura impactam diretamente o desempenho de vendas. Isso sugere uma oportunidade de expansão em estados com menor participação, mas potencial de crescimento.

## 15. Entrega esperada

Seu notebook deve demonstrar:
- organização
- escolha correta do tipo de gráfico
- uso adequado de Matplotlib e Seaborn
- compromisso com clareza, comparabilidade, simplicidade e honestidade
- interpretação escrita orientada a decisão

### Mensagem principal da aula
Não basta plotar. É preciso **comunicar o sinal no meio do ruído**. fileciteturn6file0
"""