# -*- coding: utf-8 -*-
"""jm_atividade_pratica_aula1_python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gye3pD8eePt6rzAmTR9bV5XuNyURW73J

# Atividade Prática — Aula 1  
## Python para Análise de Dados: do dado bruto à decisão estratégica

Nesta atividade, você vai aplicar os conceitos apresentados na aula usando um dataset simulado de vendas no varejo brasileiro.

**Arquivo de dados:** `vendas_brasil_aula1.csv`  
**Objetivo:** praticar leitura de dados, inspeção inicial, qualidade dos dados, KPIs e escolha de visualizações.

---
### O que você vai treinar
- Entender o pipeline básico de análise
- Inspecionar um dataset com `pandas`
- Identificar problemas de qualidade de dados
- Definir KPIs de negócio
- Escolher gráficos adequados para responder perguntas do gestor

## Instruções
1. Faça upload do arquivo `vendas_brasil_aula1.csv` no Google Colab ou deixe-o na mesma pasta do notebook.
2. Execute as células na ordem.
3. Responda às perguntas **no próprio notebook**, em células de texto ou código.
4. Sempre que possível, explique **o que o resultado significa para o negócio**.

## Dataset utilizado

O arquivo contém registros de vendas com as seguintes colunas:

- `Data_Venda`: data da venda
- `Canal_Venda`: canal comercial
- `UF`: estado da venda
- `Produto`: produto vendido
- `Preco_Unitario`: preço unitário
- `Quantidade`: quantidade vendida
- `Custo_Unitario`: custo unitário do item
- `Receita`: valor total da venda
- `Lucro`: lucro total da venda

> Atenção: o dataset foi preparado com **alguns problemas de qualidade propositalmente**, para que você pratique inspeção e limpeza.

## 1) Preparação do ambiente
Execute a célula abaixo para importar a biblioteca principal da atividade.
"""

import pandas as pd

"""## 2) Leitura do arquivo
Altere o caminho do arquivo, se necessário.
"""

df = pd.read_csv("vendas_brasil_aula1.csv")
df.info()

"""## 3) Atividade 1 — Entendendo o dataset

Responda às perguntas abaixo usando código:

1. Quantas linhas e colunas existem no dataset?
2. Quais são os nomes das colunas?
3. Quais são os tipos de dados de cada coluna?
> Dica: use `shape`, `columns` e `info()`.
"""

# Sua resposta aqui
1- 9 colunas e 300 Linhas
2- Data_Venda, Canal_Venda, UF, Produto, Preco_Unitario, Quantidade, Custo_Unitario, Receita e Lucro.
3- Float, int e object.

df = pd.read_csv("vendas_brasil_aula1.csv")
df.isnull().sum()

"""## 4) Atividade 2 — Qualidade dos dados

Agora investigue se existem problemas de qualidade.

Responda:

1. Existem valores nulos?
2. Em quais colunas eles aparecem?
3. Existem categorias escritas de formas diferentes para o mesmo canal de venda?
> Dica: use `isnull().sum()` e `value_counts()`.
"""

from types import SimpleNamespace
# Sua resposta aqui
1- Sim
2- Data_Venda, Produto, Quantidade, Custo_Unitario, Receita e Lucro.
3- Sim! Loja Física,E-Commerce, Whatsapp e Marketplace.

df = pd.read_csv("vendas_brasil_aula1.csv")
df["Receita"].sum()

df = pd.read_csv("vendas_brasil_aula1.csv")
df["Lucro"].sum()

df = pd.read_csv("vendas_brasil_aula1.csv")
df["Receita"].mean()

df = pd.read_csv("vendas_brasil_aula1.csv")
df["Quantidade"].sum()

"""## 5) Atividade 3 — KPIs do negócio

Considere que você é analista de um varejista e precisa apresentar indicadores para a gestão.

Calcule os seguintes KPIs:

1. **Receita total**
2. **Lucro total**
3. **Ticket médio** (`Receita média por registro`)
4. **Quantidade total vendida**

Depois, escreva uma breve interpretação:
- O desempenho geral parece positivo?
- Receita e lucro caminham juntos?
"""

# Sua resposta aqui
1- 707535.36
2- 189625.88
3- 2358.4512
4- 502

Sim, pois o lucro é maior que a receita.
Podem caminhar juntos, mas não proporcionalmente.

df = pd.read_csv("vendas_brasil_aula1.csv")
df.groupby("Canal_Venda")["Receita"].sum()

df = pd.read_csv("vendas_brasil_aula1.csv")
df.groupby("Produto")["Receita"].sum()

df = pd.read_csv("vendas_brasil_aula1.csv")
df.groupby("UF")["Receita"].sum()

"""## 6) Atividade 4 — Respondendo perguntas do gestor com dados

Use o dataset para responder:

1. **Qual canal gera mais receita?**
2. **Qual produto gera mais lucro?**
3. **Quais UFs concentram maior receita?**

Para cada resposta:
- mostre o código;
- apresente o resultado;
- escreva uma interpretação curta.
"""

# Sua resposta aqui
1- E-Commerce
2- Notebook
3- SP, RJ e MG.

"""## 7) Atividade 5 — Escolhendo a visualização certa

Sem necessariamente construir os gráficos ainda, responda:

a) Qual gráfico você usaria para mostrar a **evolução da receita ao longo do tempo**?  
b) Qual gráfico você usaria para **comparar a receita entre canais de venda**?  
c) Qual gráfico você usaria para mostrar a **distribuição dos preços unitários**?

Em seguida, gere **ao menos um gráfico** com `pandas` ou `matplotlib`.
"""

df.groupby("Canal_Venda")["Receita"].sum().plot()

# Sua resposta aqui
a) Gráfico de Linha
b) Gráfico de Barras
c) Gráfico de Barras

"""## Desafio extra (opcional)

Faça uma pequena limpeza no dataset:

- trate valores nulos;
- padronize os nomes dos canais de venda;
- converta `Data_Venda` para formato de data.

Depois, compare os resultados **antes e depois da limpeza**.
"""

# Sua resposta aqui

# deixar tudo minúsculo (ex: E-commerce → e-commerce)
df["Canal_Venda"] = df["Canal_Venda"].str.lower()
# tirar espaços extras
df["Canal_Venda"] = df["Canal_Venda"].str.strip()
# preencher valores vazios
df["Canal_Venda"] = df["Canal_Venda"].fillna("desconhecido")
df["UF"] = df["UF"].fillna("desconhecido")
# preencher preço com a média
df["Preco_Unitario"] = df["Preco_Unitario"].fillna(df["Preco_Unitario"].mean())
# transformar data em formato de data
df["Data_Venda"] = pd.to_datetime(df["Data_Venda"])

"""## Entrega esperada

Ao final, seu notebook deve conter:

- leitura do dataset;
- inspeção inicial;
- análise de qualidade dos dados;
- cálculo de KPIs;
- respostas às perguntas de negócio;
- pelo menos um gráfico;
- comentários interpretando os resultados.

---
### Reflexão final
Explique em 4 a 6 linhas:

**Por que uma análise de dados não deve se limitar a “fazer gráficos bonitos”?**


"""

# Sua resposta aqui

Uma análise de dados não é só fazer gráficos bonitos, porque o mais importante é entender o que os dados estão mostrando para ajudar nas decisões.
Se o gráfico não tiver contexto, pode acabar sendo interpretado de forma errada.
Também é muito importante garantir que os dados estejam corretos antes de analisar.
Além disso, é preciso relacionar os números com o que acontece no negócio.
Os dados só fazem sentido quando ajudam a responder perguntas importantes e tomar decisões melhores.