# -*- coding: utf-8 -*-
"""jm_atividade_pratica_aula3_limpeza.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NqfYLIdQUXp_lWIg-xAc-6fED3aZKIYk

# Atividade Prática — Aula 3: Limpeza, Preparação e Qualidade dos Dados com Pandas

Esta atividade foi construída com base nos slides da Aula 3, que destacam a **limpeza como a fundação invisível** de qualquer dashboard confiável. O objetivo aqui não é apenas "fazer funcionar", mas tomar decisões conscientes sobre tipos, valores ausentes, duplicidades, variáveis derivadas e exportação da base limpa. fileciteturn2file0

## Regras desta atividade
- Você deve **construir os códigos**.
- O notebook orienta os passos, mas não entrega as soluções prontas.
- Sempre que fizer uma decisão de limpeza, **documente o porquê** em comentário ou célula markdown.
- Ao final, exporte uma base limpa para uso nas próximas aulas.

## Dataset desta atividade
Arquivo bruto: `vendas_brasil_aula3_bruto.csv`

## 1. Preparação do ambiente

Importe as bibliotecas necessárias para trabalhar com:
- leitura de dados
- tratamento de nulos
- identificação de infinitos
- exportação do resultado final

**Sugestão:** Pandas e NumPy já resolvem toda a atividade.
"""

# Escreva aqui suas importações
import pandas as pd
import numpy as np

"""## 2. Leitura da base bruta

Leia o arquivo `vendas_brasil_aula3_bruto.csv` em um DataFrame chamado `df`.

Depois:
1. Exiba as primeiras linhas
2. Exiba as últimas linhas
3. Observe visualmente se já existem sinais de sujeira

"""

# Leia o CSV e faça uma inspeção inicial
df = pd.read_csv('vendas_brasil_aula3_bruto.csv')

df.head()
df.tail()

"""## 3. Check-up inicial do dataset

Com base no checklist de um dataset "clean" apresentado na aula, faça um diagnóstico inicial da base. fileciteturn2file0

### Sua missão
Use comandos que permitam responder:
- Qual é o tamanho da base?
- Quais são os tipos atuais das colunas?
- Existem valores nulos?
- Há colunas com tipo inadequado?
- Há algo que pareça impedir análises confiáveis?

"""

# Faça aqui o check-up inicial: shape, info, dtypes, isna, etc.
df.shape

df.info()

df.dtypes

df.isna().sum()

df.describe(include='all')

"""## 4. Batalha 1 — A tirania dos tipos de dados

Nos slides, vimos que datas não podem ser tratadas como texto e que números em formato string quebram análises. fileciteturn2file0

### Tarefa
Converta corretamente, quando fizer sentido:
- `data`
- `receita`
- `lucro`
- `quantidade`

### Orientação
- Investigue valores estranhos antes de converter
- Pense no uso de `errors='coerce'`
- Registre em markdown ou comentário quais problemas encontrou

"""

# Explore valores problemáticos e faça as conversões de tipo
# Data
df['data'] = pd.to_datetime(df['data'], errors='coerce')

# Remover possíveis símbolos antes de converter
df['receita'] = df['receita'].astype(str).str.replace(',', '.')
df['receita'] = pd.to_numeric(df['receita'], errors='coerce')

df['lucro'] = df['lucro'].astype(str).str.replace(',', '.')
df['lucro'] = pd.to_numeric(df['lucro'], errors='coerce')

df['quantidade'] = pd.to_numeric(df['quantidade'], errors='coerce')

"""### Reflexão curta
Explique:
1. Por que deixar `data` como texto pode quebrar análises temporais?
Datas como texto impedem ordenação e análise temporal (ex: por mês/ano).
2. Por que deixar `receita` como string pode distorcer cálculos?
Receita como string impede soma, média e cálculos financeiros.

## 5. Batalha 2 — O enigma dos valores ausentes

A aula reforça que valores ausentes não devem ser tratados automaticamente; a decisão precisa ser justificada. fileciteturn2file0

### Tarefa
1. Mapeie os valores ausentes por coluna
2. Identifique quais colunas críticas têm nulos
3. Defina uma estratégia para cada caso:
   - remover linhas?
   - preencher?
   - manter?
4. Justifique cada escolha

### Dica
Evite decisões automáticas sem análise de contexto.
"""

# Investigue os nulos e aplique aqui sua estratégia de tratamento
df.isna().sum()

# Remover linhas sem data (crítico)
df = df.dropna(subset=['data'])

# Preencher valores numéricos com 0 (se fizer sentido)
df['receita'] = df['receita'].fillna(0)
df['lucro'] = df['lucro'].fillna(0)

# Quantidade também pode ser 0
df['quantidade'] = df['quantidade'].fillna(0)

"""### Registro reflexivo
Escreva aqui sua justificativa para o tratamento dos nulos:
- Em quais colunas você removeu linhas?
Sem data
- Em quais colunas você preencheu valores?
receita e lucro com 0
- Em quais situações decidiu manter o nulo?
categorias

## 6. Batalha 3 — O ataque dos clones (duplicidades)

A aula alerta que nem toda duplicidade é erro automático: pode haver compra legítima repetida ou dupla inserção do sistema. fileciteturn2file0

### Tarefa
1. Investigue se há linhas duplicadas
2. Analise se a duplicidade parece nociva para os KPIs
3. Escolha uma estratégia:
   - remover duplicidades totais?
   - remover apenas com base em certas colunas?
   - manter?
4. Justifique a decisão
removi duplicadas completas pois podem inflar métricas como receita e lucro.
"""

# Investigue duplicidades e trate o problema conscientemente
df.duplicated().sum()
df = df.drop_duplicates()

"""## 7. Padronização de categorias

Os slides mostram que categorias duplicadas ou mal escritas podem distorcer rankings e filtros. fileciteturn2file0

### Tarefa
Inspecione e padronize, se necessário:
- `uf`
- `canal`
- `categoria`

### Pense em:
- maiúsculas e minúsculas
- espaços extras
- acentuação / variações
- categorias equivalentes escritas de formas diferentes

"""

# Faça aqui a padronização de categorias
# Remover espaços e padronizar
df['uf'] = df['uf'].str.strip().str.upper()
df['canal'] = df['canal'].str.strip().str.lower()
df['categoria'] = df['categoria'].str.strip().str.lower()

"""## 8. Subindo de nível — Criação de variáveis derivadas

Depois da limpeza, é hora de enriquecer a base com variáveis úteis para análise. fileciteturn2file0

### Tarefa
Crie, se possível:
- `ano`
- `mes`
- `ano_mes`
- `margem_lucro`

### Atenção
A criação de `margem_lucro` exige cuidado com divisões por zero e possíveis valores infinitos.

"""

# Crie aqui as variáveis derivadas
df['ano'] = df['data'].dt.year
df['mes'] = df['data'].dt.month
df['ano_mes'] = df['data'].dt.to_period('M')

# Margem de lucro
df['margem_lucro'] = df['lucro'] / df['receita']

# Tratar infinito
df['margem_lucro'] = df['margem_lucro'].replace([np.inf, -np.inf], np.nan)

"""### Reflexão técnica
Explique:
1. O que pode acontecer ao calcular margem de lucro quando a receita é zero?
Se receita = 0 a divisão gera infinito
2. Como você decidiu tratar esse caso?
Tratei substituindo por Nulo para evitar distorção

## 9. Seleção final — Menos é mais

A aula propõe que nem toda coluna precisa seguir para a base analítica final. fileciteturn2file0

### Tarefa
Crie um DataFrame final, por exemplo `df_clean` ou `df_dash`, contendo apenas as colunas estritamente necessárias para análises de negócio.

**Sugestão de raciocínio:**
- Quais colunas ajudam a responder perguntas de negócio?
- Quais colunas são operacionais, auxiliares ou dispensáveis?
- O que precisa existir para as próximas aulas de visualização e dashboard?
"""

# Selecione aqui a base final com as colunas escolhidas
df_clean = df[['data', 'ano', 'mes', 'ano_mes', 'uf', 'canal', 'categoria',
               'receita', 'lucro', 'quantidade', 'margem_lucro']]

"""## 10. Validação final da base limpa

Antes de exportar, faça uma checagem final.

### Verifique:
- os tipos estão corretos?
- ainda há nulos problemáticos?
- ainda há duplicidades nocivas?
- existe algum infinito em `margem_lucro`?
- a base está pronta para ser usada em análises e dashboards?

"""

# Faça aqui a validação final da base limpa
df_clean.info()

df_clean.isna().sum()

df_clean.duplicated().sum()

np.isinf(df_clean['margem_lucro']).sum()

"""## 11. Exportação da base "Clean"

Agora gere o arquivo final da base tratada.

### Tarefa
Exporte sua base limpa com o nome:

`vendas_brasil_aula3_clean.csv`

### Observação
Esse arquivo será o selo de qualidade do seu trabalho desta aula.

"""

# Exporte aqui sua base final sem índice
df_clean.to_csv('vendas_brasil_aula3_clean.csv', index=False)

"""## 12. Conclusão e registro reflexivo

Escreva um pequeno texto respondendo:

1. Quais foram os principais problemas de qualidade encontrados?
Tipos errados, Valores nulos.Possíveis duplicidades e Categorias inconsistentes.
2. Qual decisão de limpeza foi mais difícil?
Como tratar nulos sem perder informação relevante
3. Que impacto essas falhas poderiam causar em um dashboard?
Indicadores errados, Filtros quebrados e Análises temporais impossíveis
4. Por que a etapa de limpeza é considerada a "fundação invisível" do projeto?
Sem dados confiáveis, qualquer análise ou dashboard será enganoso

## 13. Desafio extra (opcional)

Use sua base limpa para responder rapidamente:

- Qual UF concentra maior receita?
- Qual canal gera maior lucro?
- Existe algum mês com desempenho claramente acima dos demais?

Você pode responder com tabelas simples ou pequenos agrupamentos.
"""

# Desafio extra opcional
# UF com maior receita
df_clean.groupby('uf')['receita'].sum().sort_values(ascending=False)

# Canal com maior lucro
df_clean.groupby('canal')['lucro'].sum().sort_values(ascending=False)

# Receita por mês
df_clean.groupby('ano_mes')['receita'].sum().sort_values(ascending=False)